# Generated by Django 4.2.1 on 2024-05-21 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobSyncApp', '0002_comuna_alter_customuser_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajo', models.CharField(max_length=100)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('rut_titular', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('pendiente', 'Pendiente'), ('completado', 'Completado')], default='sin_asignar', max_length=20)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobSyncApp.comuna')),
            ],
        ),
    ]
